version: '3'

services:
  h2:
    image: oscarfonts/h2:1.4.199
    ports:
      - "81:81"
      - "1521:1521"
    volumes:
      - ./data:/opt/h2-data
    restart: always
    container_name: h2
    environment:
      - H2_OPTIONS=-ifNotExists

